# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'forward' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for forward

pod 'JXCategoryView'
pod 'IQKeyboardManager'
pod 'AxcAE_TabBar'
pod 'Masonry'
pod 'SDWebImage', '>= 5.0.0'
pod 'HBDNavigationBar', '~> 1.7.7'
pod 'YPNavigationBarTransition', '~> 2.0'
pod 'FSPagerView'

pod 'MJExtension'
pod 'BRPickerView'
pod 'Mantle', '~> 2.1.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'AFNetworking', '<= 3.2.1'
pod 'MJRefresh'

end
